version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: atm-db
    env_file: 
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./scripts/10_init.sql:/docker-entrypoint-initdb.d/10_init.sql