version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: atm-db
    env_file: 
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./scripts/10_init.sql:/docker-entrypoint-initdb.d/10_init.sql
      - ./scripts/20_fill_dictionaries.sql:/docker-entrypoint-initdb.d/20_fill_dictionaries.sql
      - ./scripts/30_fill_data.sql:/docker-entrypoint-initdb.d/30_fill_data.sql
      - ./scripts/40_fill_accounts.sql:/docker-entrypoint-initdb.d/40_fill_accounts.sql