INSERT INTO atm.locations (code, city, region, country_name) VALUES ('AF', null, null, 'Afghanistan'),
('AL', null, null, 'Albania'),
('DZ', null, null, 'Algeria'),
('AS', null, null, 'American Samoa'),
('AD', null, null, 'Andorra'),
('AO', null, null, 'Angola'),
('AI', null, null, 'Anguilla'),
('AQ', null, null, 'Antarctica'),
('AG', null, null, 'Antigua and Barbuda'),
('AR', null, null, 'Argentina'),
('AM', null, null, 'Armenia'),
('AW', null, null, 'Aruba'),
('AU', null, null, 'Australia'),
('AT', null, null, 'Austria'),
('AZ', null, null, 'Azerbaijan'),
('BS', null, null, 'Bahamas'),
('BH', null, null, 'Bahrain'),
('BD', null, null, 'Bangladesh'),
('BB', null, null, 'Barbados'),
('BY', null, null, 'Belarus'),
('BE', null, null, 'Belgium'),
('BZ', null, null, 'Belize'),
('BJ', null, null, 'Benin'),
('BM', null, null, 'Bermuda'),
('BT', null, null, 'Bhutan'),
('BA', null, null, 'Bosnia and Herzegovina'),
('BW', null, null, 'Botswana'),
('BV', null, null, 'Bouvet Island'),
('BR', null, null, 'Brazil'),
('IO', null, null, 'British Indian Ocean Territory'),
('BN', null, null, 'Brunei Darussalam'),
('BG', null, null, 'Bulgaria'),
('BF', null, null, 'Burkina Faso'),
('BI', null, null, 'Burundi'),
('KH', null, null, 'Cambodia'),
('CM', null, null, 'Cameroon'),
('CA', null, null, 'Canada'),
('CV', null, null, 'Cape Verde'),
('KY', null, null, 'Cayman Islands'),
('CF', null, null, 'Central African Republic'),
('TD', null, null, 'Chad'),
('CL', null, null, 'Chile'),
('CN', null, null, 'China'),
('CX', null, null, 'Christmas Island'),
('CC', null, null, 'Cocos (Keeling) Islands'),
('CO', null, null, 'Colombia'),
('KM', null, null, 'Comoros'),
('CG', null, null, 'Congo'),
('CK', null, null, 'Cook Islands'),
('CR', null, null, 'Costa Rica'),
('CI', null, null, 'CÃ´te d''Ivoire'),
('HR', null, null, 'Croatia'),
('CU', null, null, 'Cuba'),
('CW', null, null, 'CuraÃ§ao'),
('CY', null, null, 'Cyprus'),
('CZ', null, null, 'Czech Republic'),
('DK', null, null, 'Denmark'),
('DJ', null, null, 'Djibouti'),
('DM', null, null, 'Dominica'),
('DO', null, null, 'Dominican Republic'),
('EC', null, null, 'Ecuador'),
('EG', null, null, 'Egypt'),
('SV', null, null, 'El Salvador'),
('GQ', null, null, 'Equatorial Guinea'),
('ER', null, null, 'Eritrea'),
('EE', null, null, 'Estonia'),
('ET', null, null, 'Ethiopia'),
('FK', null, null, 'Falkland Islands (Malvinas)'),
('FO', null, null, 'Faroe Islands'),
('FJ', null, null, 'Fiji'),
('FI', null, null, 'Finland'),
('FR', null, null, 'France'),
('GF', null, null, 'French Guiana'),
('PF', null, null, 'French Polynesia'),
('TF', null, null, 'French Southern Territories'),
('GA', null, null, 'Gabon'),
('GM', null, null, 'Gambia'),
('GE', null, null, 'Georgia'),
('DE', null, null, 'Germany'),
('GH', null, null, 'Ghana'),
('GI', null, null, 'Gibraltar'),
('GR', null, null, 'Greece'),
('GL', null, null, 'Greenland'),
('GD', null, null, 'Grenada'),
('GP', null, null, 'Guadeloupe'),
('GU', null, null, 'Guam'),
('GT', null, null, 'Guatemala'),
('GG', null, null, 'Guernsey'),
('GN', null, null, 'Guinea'),
('GW', null, null, 'Guinea-Bissau'),
('GY', null, null, 'Guyana'),
('HT', null, null, 'Haiti'),
('HM', null, null, 'Heard Island and McDonald Islands'),
('VA', null, null, 'Holy See (Vatican City State)'),
('HN', null, null, 'Honduras'),
('HK', null, null, 'Hong Kong'),
('HU', null, null, 'Hungary'),
('IS', null, null, 'Iceland'),
('IN', null, null, 'India'),
('ID', null, null, 'Indonesia'),
('IQ', null, null, 'Iraq'),
('IE', null, null, 'Ireland'),
('IM', null, null, 'Isle of Man'),
('IL', null, null, 'Israel'),
('IT', null, null, 'Italy'),
('JM', null, null, 'Jamaica'),
('JP', null, null, 'Japan'),
('JE', null, null, 'Jersey'),
('JO', null, null, 'Jordan'),
('KZ', null, null, 'Kazakhstan'),
('KE', null, null, 'Kenya'),
('KI', null, null, 'Kiribati'),
('KW', null, null, 'Kuwait'),
('KG', null, null, 'Kyrgyzstan'),
('LA', null, null, 'Lao People''s Democratic Republic'),
('LV', null, null, 'Latvia'),
('LB', null, null, 'Lebanon'),
('LS', null, null, 'Lesotho'),
('LR', null, null, 'Liberia'),
('LY', null, null, 'Libya'),
('LI', null, null, 'Liechtenstein'),
('LT', null, null, 'Lithuania'),
('LU', null, null, 'Luxembourg'),
('MO', null, null, 'Macao'),
('MG', null, null, 'Madagascar'),
('MW', null, null, 'Malawi'),
('MY', null, null, 'Malaysia'),
('MV', null, null, 'Maldives'),
('ML', null, null, 'Mali'),
('MT', null, null, 'Malta'),
('MH', null, null, 'Marshall Islands'),
('MQ', null, null, 'Martinique'),
('MR', null, null, 'Mauritania'),
('MU', null, null, 'Mauritius'),
('YT', null, null, 'Mayotte'),
('MX', null, null, 'Mexico'),
('MC', null, null, 'Monaco'),
('MN', null, null, 'Mongolia'),
('ME', null, null, 'Montenegro'),
('MS', null, null, 'Montserrat'),
('MA', null, null, 'Morocco'),
('MZ', null, null, 'Mozambique'),
('MM', null, null, 'Myanmar'),
('NA', null, null, 'Namibia'),
('NR', null, null, 'Nauru'),
('NP', null, null, 'Nepal'),
('NL', null, null, 'Netherlands'),
('NC', null, null, 'New Caledonia'),
('NZ', null, null, 'New Zealand'),
('NI', null, null, 'Nicaragua'),
('NE', null, null, 'Niger'),
('NG', null, null, 'Nigeria'),
('NU', null, null, 'Niue'),
('NF', null, null, 'Norfolk Island'),
('MP', null, null, 'Northern Mariana Islands'),
('NO', null, null, 'Norway'),
('OM', null, null, 'Oman'),
('PK', null, null, 'Pakistan'),
('PW', null, null, 'Palau'),
('PA', null, null, 'Panama'),
('PG', null, null, 'Papua New Guinea'),
('PY', null, null, 'Paraguay'),
('PE', null, null, 'Peru'),
('PH', null, null, 'Philippines'),
('PN', null, null, 'Pitcairn'),
('PL', null, null, 'Poland'),
('PT', null, null, 'Portugal'),
('PR', null, null, 'Puerto Rico'),
('QA', null, null, 'Qatar'),
('RE', null, null, 'RÃ©union'),
('RO', null, null, 'Romania'),
('RU', null, null, 'Russian Federation'),
('RW', null, null, 'Rwanda'),
('BL', null, null, 'Saint BarthÃ©lemy'),
('KN', null, null, 'Saint Kitts and Nevis'),
('LC', null, null, 'Saint Lucia'),
('MF', null, null, 'Saint Martin (French part)'),
('PM', null, null, 'Saint Pierre and Miquelon'),
('VC', null, null, 'Saint Vincent and the Grenadines'),
('WS', null, null, 'Samoa'),
('SM', null, null, 'San Marino'),
('ST', null, null, 'Sao Tome and Principe'),
('SA', null, null, 'Saudi Arabia'),
('SN', null, null, 'Senegal'),
('RS', null, null, 'Serbia'),
('SC', null, null, 'Seychelles'),
('SL', null, null, 'Sierra Leone'),
('SG', null, null, 'Singapore'),
('SX', null, null, 'Sint Maarten (Dutch part)'),
('SK', null, null, 'Slovakia'),
('SI', null, null, 'Slovenia'),
('SB', null, null, 'Solomon Islands'),
('SO', null, null, 'Somalia'),
('ZA', null, null, 'South Africa'),
('GS', null, null, 'South Georgia and the South Sandwich Islands'),
('SS', null, null, 'South Sudan'),
('ES', null, null, 'Spain'),
('LK', null, null, 'Sri Lanka'),
('SD', null, null, 'Sudan'),
('SR', null, null, 'Suriname'),
('SJ', null, null, 'Svalbard and Jan Mayen'),
('SZ', null, null, 'Swaziland'),
('SE', null, null, 'Sweden'),
('CH', null, null, 'Switzerland'),
('SY', null, null, 'Syrian Arab Republic'),
('TJ', null, null, 'Tajikistan'),
('TH', null, null, 'Thailand'),
('TL', null, null, 'Timor-Leste'),
('TG', null, null, 'Togo'),
('TK', null, null, 'Tokelau'),
('TO', null, null, 'Tonga'),
('TT', null, null, 'Trinidad and Tobago'),
('TN', null, null, 'Tunisia'),
('TR', null, null, 'Turkey'),
('TM', null, null, 'Turkmenistan'),
('TC', null, null, 'Turks and Caicos Islands'),
('TV', null, null, 'Tuvalu'),
('UG', null, null, 'Uganda'),
('UA', null, null, 'Ukraine'),
('AE', null, null, 'United Arab Emirates'),
('GB', null, null, 'United Kingdom'),
('US', null, null, 'United States'),
('UM', null, null, 'United States Minor Outlying Islands'),
('UY', null, null, 'Uruguay'),
('UZ', null, null, 'Uzbekistan'),
('VU', null, null, 'Vanuatu'),
('VN', null, null, 'Viet Nam'),
('WF', null, null, 'Wallis and Futuna'),
('EH', null, null, 'Western Sahara'),
('YE', null, null, 'Yemen'),
('ZM', null, null, 'Zambia'),
('ZW', null, null, 'Zimbabwe'),
('UA', 'Kyiv', 'Kyiv', 'Ukraine'),
('UA', 'Rivne', 'Rivne', 'Ukraine'),
('UA', 'Lviv', 'Lviv', 'Ukraine'),
('UA', 'Poltava', 'Poltava', 'Ukraine');

INSERT INTO atm.banks(title, location_id, address) VALUES
('Raiffeisen Bank', 236, '7, M. Kotsyubinskogo Str., Kyiv, 01601, Ukraine'),
('BNP Paribas Group', 236, '45, Uritskogo Str., Kyiv, 04655, Ukraine'),
('Citibank', 236, '1, Lesi Ukrayinki Pl., Kyiv, 01196, Ukraine'),
('ProCredit Bank', 236, '14, Zhilyanskaya Str., Kyiv, 01033, Ukraine'),
('PKO Bank Polskа', 236, '12/2, Grushevskogo Vul., Kyiv, 01008, Ukraine'),
('Privatbank', 236, '8, Bohomoltsa Str., Kyiv, 01024, Ukraine'),
('ABH Holdings', 236, '35, Uritskogo Str., Kiev, 03035, Ukraine');


INSERT INTO atm.users(first_name, last_name, primary_phone, additional_phone, email, status_id, language_id, timezone_id, birthday, internal_status_id, location_id, zip, address_1, address_2, ipn, document_number, document_type_id, document_date, document_authority)VALUES
('John', 'Doe', '+380674323423', '044-432-34-23', 'john.doe@example.com', 2, 171, 921, '1980-05-05', 1, 236, '03456', 'Koltsova blvd, 4, ap. 43', '', '9876734234', 'ME333222', 1, '2003-06-06', 'РВ УМВС України в Київський області'),
('Jane', 'Doe', '+380688888823', '044-999-34-23', 'jane.doe@example.com', 2, 171, 921, '1988-05-05', 1, 236, '09999', 'Pushkina blvd, 9, ap. 4', '', '9888834234', 'KO000222', 1, '2008-07-06', 'РВ УМВС України в Полтавький області');